### ISSUE TITLE
不能导出图片么？

### ISSUE THREAD

**Issue by Julyoooo** [echoma/text_sequence_diagram#2]

**Comment by echoma** [comment]
还没做这功能，暂时用截图工具凑合下吧。。。

**Comment by cuijianyong** [comment]
So cool, but export image can be use. One year passed ...  Wish your update :)

**Comment by echoma** [comment]
今天趁着周末把这个功能开发好了，不过只有下载版本支持，在线网页版是不支持的。

下载版本我还没打包，我这里暂时只有ubuntu系统，等明天把windows的打包上传到下载页面。

**Comment by echoma** [comment]
找同事帮忙测试了下，应该没问题了，已经上传新的包到下载页面了。

[下载页面](https://github.com/echoma/text_sequence_diagram/wiki/Download)

**Comment by cuijianyong** [comment]
@echoma  赞！可以使用，还增加了保存功能。
