### ISSUE TITLE
Support MacOS?

### ISSUE THREAD

**Issue by monkeyk** [echoma/text_sequence_diagram#6]
How to use text_sequence_diagram on MacOS? use linux download?

**Comment by echoma** [comment]
兄弟，我这也没有mac，所以也没办法给mac打包。 这个工具是用nwjs的做的，所以你可以下载安装nw.js，git-clone这个仓库，然后在仓库根目录执行nwjs就可以了。

**Comment by monkeyk** [comment]
收到，我试试，TKS!
